# Generated by Django 5.1.6 on 2025-03-13 08:22

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(upload_to=gallery.models.custom_upload_to),
        ),
    ]
