# Generated by Django 5.1.6 on 2025-03-07 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('data_event', models.DateField(verbose_name='Дата события')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание события')),
                ('final_place', models.IntegerField(verbose_name='Итоговое место')),
                ('tournament_name', models.CharField(max_length=200, verbose_name='Название турнира')),
                ('participants_count', models.IntegerField(verbose_name='Количество участников')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.CharField(default='Синие', max_length=100, verbose_name='Первая команда')),
                ('second_team', models.CharField(default='Команда 2', max_length=100, verbose_name='Вторая команда')),
                ('status', models.CharField(choices=[('Победа', 'Победа'), ('Ничья', 'Ничья'), ('Поражение', 'Поражение')], max_length=100, verbose_name='Статус игры')),
                ('result', models.CharField(blank=True, max_length=20, null=True, verbose_name='Результат')),
                ('date', models.DateField(verbose_name='Дата')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('tournament', models.CharField(max_length=100, verbose_name='Турнир')),
                ('stage', models.CharField(choices=[('1 тур', '1 тур'), ('2 тур', '2 тур'), ('3 тур', '3 тур'), ('4 тур', '5 тур'), ('1/8', '1/8'), ('1/4', '1/4'), ('Полуфинал', 'Полуфинал'), ('Финал', 'Финал')], default='Первый круг', max_length=100, verbose_name='Стадия турнира')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('main_photo', models.ImageField(blank=True, upload_to='player_photos/', verbose_name='Основное фото')),
                ('position', models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('MF', 'Полузащитник'), ('FW', 'Нападающий')], max_length=2, verbose_name='Амплуа')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('description', models.TextField(verbose_name='Описание команды')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Сыграно матчей')),
                ('matches_won', models.IntegerField(default=0, verbose_name='Победы')),
                ('matches_drawn', models.IntegerField(default=0, verbose_name='Ничьи')),
                ('matches_lost', models.IntegerField(default=0, verbose_name='Поражения')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.match', verbose_name='Матч')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Гол игрока',
                'verbose_name_plural': 'Голы игрока',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание фото')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='team.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Фото игроков',
                'verbose_name_plural': 'Фото игроков',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='team.Goal', to='team.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.team', verbose_name='Команда'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, upload_to='coach_photos/', verbose_name='Фото тренера')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('start_of_coaching_career', models.DateField(blank=True, null=True, verbose_name='Дата начала тренерской деятельности')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='TeamPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_photos/', verbose_name='Фото команды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание фото')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_photo', to='team.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Командные фото',
                'verbose_name_plural': 'Командные фото',
            },
        ),
        migrations.CreateModel(
            name='TeamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Командные видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание видео')),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='team_video', to='team.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Командные видео',
                'verbose_name_plural': 'Командные видео',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание видео')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_videos', to='team.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Видео игроков',
                'verbose_name_plural': 'Видео игроков',
            },
        ),
    ]
