# Generated by Django 5.1.6 on 2025-03-03 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название команды')),
                ('description', models.TextField(verbose_name='Описание команды')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Сыграно матчей')),
                ('matches_won', models.IntegerField(default=0, verbose_name='Победы')),
                ('matches_drawn', models.IntegerField(default=0, verbose_name='Ничьи')),
                ('matches_lost', models.IntegerField(default=0, verbose_name='Поражения')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='TeamPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='team_photos/', verbose_name='Фото команды')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание фото')),
            ],
            options={
                'verbose_name': 'Фото команды',
                'verbose_name_plural': 'Фото команды',
            },
        ),
        migrations.CreateModel(
            name='TeamVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('main_photo', models.ImageField(upload_to='player_photos/', verbose_name='Основное фото')),
                ('position', models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('MF', 'Полузащитник'), ('FW', 'Нападающий')], max_length=2, verbose_name='Амплуа')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')),
                ('additional_photos', models.ManyToManyField(related_name='players', to='team.photo', verbose_name='Дополнительные фото')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='team.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='team.player', verbose_name='Игрок'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='coach_photos/', verbose_name='Фото тренера')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('start_of_coaching_career', models.DateField(verbose_name='Дата начала тренерской деятельности')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='photos',
            field=models.ManyToManyField(related_name='teams', to='team.teamphoto'),
        ),
        migrations.AddField(
            model_name='team',
            name='videos',
            field=models.ManyToManyField(related_name='teams', to='team.teamvideo'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/', verbose_name='Видео')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание видео')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='team.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='additional_videos',
            field=models.ManyToManyField(related_name='players', to='team.video', verbose_name='Дополнительные видео'),
        ),
    ]
