# Generated by Django 5.1.6 on 2025-03-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamvideo',
            options={'verbose_name': 'Командные видео', 'verbose_name_plural': 'Командные видео'},
        ),
        migrations.AlterField(
            model_name='team',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='team.teamphoto'),
        ),
        migrations.AlterField(
            model_name='team',
            name='videos',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='team.teamvideo'),
        ),
        migrations.AlterField(
            model_name='teamvideo',
            name='video',
            field=models.FileField(upload_to='videos/', verbose_name='Командные видео'),
        ),
    ]
