# Generated by Django 5.1.6 on 2025-03-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('1 тур', '1 тур'), ('2 тур', '2 тур'), ('3 тур', '3 тур'), ('4 тур', '4 тур'), ('1/8', '1/8'), ('1/4', '1/4'), ('Полуфинал', 'Полуфинал'), ('Финал', 'Финал')], default='Первый круг', max_length=100, verbose_name='Стадия турнира'),
        ),
    ]
