# Generated by Django 5.1.6 on 2025-03-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_teamvideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
