# Generated by Django 5.1.6 on 2025-03-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_player_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='patronymic',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отчество'),
        ),
    ]
