# Generated by Django 5.1.6 on 2025-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_match_result_match_goals_conceded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание матча'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_conceded',
            field=models.IntegerField(default=0, verbose_name='Пропущенные мячи'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_scored',
            field=models.IntegerField(default=0, verbose_name='Забитые мячи'),
        ),
    ]
