# Generated by Django 5.1.6 on 2025-03-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_match_description_alter_match_goals_conceded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='in_the_team',
            field=models.CharField(choices=[('GK', 'Вратарь'), ('DF', 'Защитник'), ('MF', 'Полузащитник'), ('FW', 'Нападающий')], default='YES', max_length=10, verbose_name='Статус'),
        ),
    ]
