# Generated by Django 5.1.6 on 2025-03-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_coach_patronymic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='start_of_coaching_career',
            field=models.DateField(blank=True, verbose_name='Дата начала тренерской деятельности'),
        ),
    ]
