# Generated by Django 5.1.6 on 2025-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_player_in_the_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='in_the_team',
            field=models.CharField(choices=[('YES', 'В составе'), ('NO', 'Не в составе'), ('UNKNOWN', 'Статус неопределен')], default='YES', max_length=10, verbose_name='Статус'),
        ),
    ]
