# Generated by Django 5.1.6 on 2025-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_coach_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='start_of_coaching_career',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала тренерской деятельности'),
        ),
    ]
