# Generated by Django 5.1.6 on 2025-03-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_coach_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='player_photos/', verbose_name='Основное фото'),
        ),
    ]
