# Generated by Django 5.1.6 on 2025-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_player_in_the_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер игрока'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('team', 'number'), name='unique_team_number'),
        ),
    ]
