# Generated by Django 5.2.4 on 2025-07-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_player_number_player_unique_team_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='career',
            field=models.TextField(blank=True, null=True, verbose_name='Карьера'),
        ),
    ]
