# Generated by Django 5.1.6 on 2025-03-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_player_main_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, upload_to='coach_photos/', verbose_name='Фото тренера'),
        ),
    ]
