# Generated by Django 5.1.6 on 2025-03-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_coach_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='teams', to='team.teamphoto'),
        ),
        migrations.AlterField(
            model_name='team',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='teams', to='team.teamvideo'),
        ),
    ]
