# Generated by Django 5.1.6 on 2025-03-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_alter_player_additional_photos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото игроков', 'verbose_name_plural': 'Фото игроков'},
        ),
        migrations.AlterModelOptions(
            name='teamphoto',
            options={'verbose_name': 'Командные фото', 'verbose_name_plural': 'Командные фото'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео игроков', 'verbose_name_plural': 'Видео игроков'},
        ),
    ]
