# Generated by Django 5.1.6 on 2025-03-04 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_alter_photo_options_alter_teamphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='teamphoto',
            options={'verbose_name': 'Фото команды', 'verbose_name_plural': 'Фото команды'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='team.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='team.player', verbose_name='Игрок'),
        ),
    ]
