# Generated by Django 5.1.6 on 2025-03-04 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_alter_photo_options_alter_teamphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
    ]
