# Generated by Django 5.1.6 on 2025-03-04 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_alter_player_options_remove_player_additional_photos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'Фото игроков', 'verbose_name_plural': 'Фото игроков'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AlterModelOptions(
            name='teamphoto',
            options={'verbose_name': 'Командные фото', 'verbose_name_plural': 'Командные фото'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео игроков', 'verbose_name_plural': 'Видео игроков'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='team.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='video',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_videos', to='team.player', verbose_name='Игрок'),
        ),
    ]
