name: Deploy Django to VPS

on:
  push:
    branches: [ main ]

env:
  PROJECT_DIR: /var/www/team_site/football_team
  REPO_URL: https://github.com/mininik08inv/team_site.git

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Update .env file
      run: |
      ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
      echo '${{ secrets.ENV_FILE }}' > $PROJECT_DIR/.env
    "
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Execute deployment script
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
          cd $PROJECT_DIR &&
          git pull origin main &&
          source venv/bin/activate &&
          pip install -r requirements.txt &&
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          sudo systemctl restart gunicorn &&
          sudo systemctl restart nginx
        "
